version: '3.8'

services:
  vibze-app:
    image: vibze:latest
    container_name: vibze-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - vibze-network

  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vibze
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=root
    networks:
      - vibze-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the initialization script

networks:
  vibze-network:
    driver: bridge
